"""upgrade to 2048-dim vectors

Revision ID: a1b2c3d4e5f6
Revises: e5875039f9d9
Create Date: 2024-11-16 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'e5875039f9d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Upgrade embeddings from 768 to 2048 dimensions

    WARNING: This will clear existing embeddings as they need to be regenerated
    with the new model to maintain the correct dimensionality.
    """
    # First, set all existing embeddings to NULL
    # This is necessary because we can't directly resize vectors
    op.execute("UPDATE memories SET embedding = NULL")

    # Drop the old column
    op.drop_column('memories', 'embedding')

    # Add new column with 2048 dimensions
    op.add_column(
        'memories',
        sa.Column('embedding', Vector(2048), nullable=True)
    )

    # Add comment explaining the upgrade
    op.execute("""
        COMMENT ON COLUMN memories.embedding IS
        'Upgraded to 2048-dimensional vectors for advanced NLP and semantic search.
        Embeddings will be regenerated by background workers using the updated model.'
    """)


def downgrade() -> None:
    """
    Downgrade embeddings from 2048 to 768 dimensions

    WARNING: This will also clear existing embeddings.
    """
    # Set all embeddings to NULL
    op.execute("UPDATE memories SET embedding = NULL")

    # Drop the 2048-dim column
    op.drop_column('memories', 'embedding')

    # Add back the 768-dim column
    op.add_column(
        'memories',
        sa.Column('embedding', Vector(768), nullable=True)
    )

    # Add comment
    op.execute("""
        COMMENT ON COLUMN memories.embedding IS
        'Downgraded to 768-dimensional vectors.'
    """)
